name: Tests

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
  pull_request:
    branches-ignore: []
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.8, 3.9, '3.10']
      fail-fast: false

    steps:

    - name: install graphviz
      run: |
        sudo apt-get install -y graphviz

    - name: checkout git repo
      uses: actions/checkout@v2

    - name: conda/mamba
      uses: mamba-org/provision-with-micromamba@main
      with:
          environment-file: environment.yml
          extra-specs: |
            python=${{ matrix.python }}

    - name: install package itself
      shell: bash -l {0}
      run: |
        pip install .

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install coveralls pytest-cov pytest pytest-xdist
        pip install damona
        
    - name: Activate Damona
      run: |
        bash
        damona  # this creates the bash script
        echo " source ~/.config/damona/damona.sh" >> ~/.bashrc
    - name: Create env, install bcl2fastq
      run: |
        bash
        damona create TEST
        damona activate TEST
        damona install bcl2fastq
      env:
        DAMONA_EXE: /usr/share/miniconda/bin/damona
        DAMONA_PATH: /home/runner/.config/damona
        DAMONA_SINGULARITY_OPTIONS: ""
        DAMONA_ENV: /home/runner/.config/damona/envs/TEST
        DAMONA_SHELL_INFO: "bash"
    - name: install package itself
      run: |
         pip install .

    - name: testing
      run: |
        damona activate TEST
        pytest --cov-report term --cov=sequana_pipelines.demultiplex
      env:
        DAMONA_EXE: /usr/share/miniconda/bin/damona
        DAMONA_PATH: /home/runner/.config/damona
        DAMONA_SINGULARITY_OPTIONS: ""
        DAMONA_ENV: /home/runner/.config/damona/envs/TEST
        DAMONA_SHELL_INFO: "bash"

    - name: coveralls
      run: |
        echo $COVERALLS_REPO_TOKEN
        coveralls --service=github
      env:
          GITHUB_TOKEN: ${{ github.token }}
